---
- name: create database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "VinceBase"
    state: present

- name: create user - Vincent
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: Vincent
    password: test13012
    priv: '*.*:ALL'
    state: present
