---
- name: create database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ user }}Base"
    state: present

- name: create user - {{ user }}
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ user }}"
    password: test13012
    priv: '*.*:ALL'
    state: present
